name: CI
on:
  push:
    branches:
      - main
      - master
    tags:
      - "*"
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
          